---
- name: Validar Conexion a VMware ESXi 8
  hosts: esxi-01.pclinux.com
  gather_facts: false
  tasks:
    - name: Instalar pyvmomi dinamicamente
      ansible.builtin.pip:
        name: pyvmomi
        state: present
      delegate_to: localhost

    - name: Obtener hechos del host ESXi
      community.vmware.vmware_host_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
      delegate_to: localhost
      register: host_facts
    - name: Mostrar resultado
      ansible.builtin.debug:
        msg: "Conectado a {{ host_facts.ansible_facts.product_name }} version {{ host_facts.ansible_facts.product_version }}"
