---
- name: Validar Conexion a VMware ESXi 8
  hosts: esxi-01.pclinux.com
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Consultar API de VMware
      community.vmware.vmware_host_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
      delegate_to: localhost
      register: host_facts

    - name: ¡LOGRADO!
      ansible.builtin.debug:
        msg: "Conectado a {{ host_facts.ansible_facts.product_full_name }}"
